version: "3"
services:
  leader:
    container_name: ${CONTAINER_NAME}-leader
    image: ravendb/ravendb:${RAVENDB_VERSION}
    ports:
      - 8081:8080
      - 38889:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://leader:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://leader:38888
  follower1:
    container_name: ${CONTAINER_NAME}-follower1
    image: ravendb/ravendb:${RAVENDB_VERSION}
    depends_on:
      - leader
    ports:
      - 8082:8080
      - 38890:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://follower1:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://follower1:38888
  follower2:
    container_name: ${CONTAINER_NAME}-follower2
    image: ravendb/ravendb:${RAVENDB_VERSION}
    depends_on:
      - leader
    ports:
      - 8083:8080
      - 38891:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://follower2:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://follower2:38888
