version: "3"
services:
  singlenode:
    container_name: ${CONTAINER_NAME}
    image: ravendb/ravendb:${RAVENDB_VERSION}
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_PublicServerUrl=http://singlenode:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://singlenode:38888