services:
  singlenode:
    container_name: ${CONTAINER_NAME}
    image: ravendb/ravendb:${RAVENDB_VERSION}
    ports:
      - 8080:8080
      - 38888:38888
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://172.28.1.1:8080"
      - "RAVEN_PublicServerUrl=http://host.docker.internal:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://172.28.1.1:38888"
      - "RAVEN_PublicServerUrl_Tcp=tcp://host.docker.internal:38888"
    networks:
      singlenode_network:
        ipv4_address: 172.28.1.1
networks:
  singlenode_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16