version: "3"
services:
  singlenode:
    container_name: ${CONTAINER_NAME}
    image: ravendb/ravendb:${RAVENDB_VERSION}
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://127.0.0.1:8080"
      - "RAVEN_ServerUrl_Tcp=tcp://127.0.0.1:38888"
  singlenodesetup:
    container_name: singlenodesetup
    image: mcr.microsoft.com/powershell:${POWERSHELL_VERSION}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${CURRENT_DIRECTORY}:${POWERSHELL_SCRIPT_DIRECTORY}
    entrypoint:
      [
        "pwsh",
        "-command",
        "&.${POWERSHELL_SCRIPT_DIRECTORY}/setup_singlenode.ps1",
        "'${LICENSE}'",
      ]
    restart: "no"
    depends_on:
      - singlenode